" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" vim-plug plugin manager (install plugins with :PlugInstall)
call plug#begin('~/.vim/plugged')

" plugins used by ThePrimeagen (youtube)
Plug 'git@github.com:Valloric/YouCompleteMe.git'    " auto-complete
Plug 'morhetz/gruvbox'
Plug 'jremmen/vim-ripgrep'  " fast grep
Plug 'tpope/vim-fugitive'   " git integration
Plug 'leafgarland/typescript-vim'  " typscript
Plug 'vim-utils/vim-man'    " man pages
Plug 'lyuts/vim-rtags'      " c++
Plug 'git@github.com:kien/ctrlp.vim.git'    " file finding
Plug 'mbbill/undotree'  " undo history visualizer/tool

" debugging
Plug 'puremourning/vimspector'

Plug 'szw/vim-maximizer'
"Plug 'KeitaNakamura/neodark.vim'
Plug 'lervag/vimtex'
"Plug 'vim-airline/vim-airline'
"Plug 'vim-airline/vim-airline-themes'
Plug 'itchyny/lightline.vim'
Plug 'sheerun/vim-polyglot'
Plug 'takac/vim-hardtime'
call plug#end()

syntax enable
set noerrorbells
set tabstop=4 softtabstop=4
set shiftwidth=4		" number of spaces for autoindent
set expandtab			" uses spaces instead of tabs
set smartindent
set number 			" show line numbers
set relativenumber
set smartcase
set incsearch                   " search on keystroke
set nowrap      " don't softbreak lines
set cursorline
highlight CursorLine ctermbg=129 cterm=bold "ctermfg=Gray
set colorcolumn=80
highlight ColorColumn ctermbg=8 guibg=lightgrey
set showmatch			" show matching parenthesis
set ignorecase
filetype plugin indent on

"set background=dark
"set autoindent			" auto indentation
"set smarttab			" use tabs at the start of a line, spaces elsewhere
"set title			" change the terminal title
"set t_Co=256
"set hlsearch                    " highlight all hits

" enable hardmode by default
let g:hardtime_default_on = 0

" Autocompletion
"set wildmode=longest,list,full
let g:ycm_autoclose_preview_window_after_completion = 1

" Splitting
set splitbelow
set splitright

"" Leader Key shortcuts
let mapleader=" "

" moving between windows (use '|' afterwards to allow comments in same line)
nnoremap <leader>h :wincmd h<CR>|    " leader + h -> switch to left window
nnoremap <leader>j :wincmd j<CR>|    " leader + j -> switch to bottom window
nnoremap <leader>k :wincmd k<CR>|    " leader + k -> switch to upper window
nnoremap <leader>l :wincmd l<CR>|    " leader + l -> switch to right window
nnoremap <leader>f :MaximizerToggle<CR>| " make window fullscreen

nnoremap <leader>u :UndotreeShow<CR>
nnoremap <leader>pv :wincmd v<bar> :Ex <bar> :vertical resize 30<CR>
nnoremap <leader>ps :Rg<SPACE>
nnoremap <silent> <leader>+ :vertical resize +5<CR>
nnoremap <silent> <leader>- :vertical resize -5<CR>

nnoremap <silent> <leader>gd :YcmCompleter GoTo<CR>
nnoremap <silent> <leader>gf :YcmCompleter FixIt<CR>

"############## Spellcheck ################
" TODO: Create spellfile, so german words can be added to the german
" dictionary

au BufNewFile,BufRead,BufEnter      *.wiki     setlocal spell      spelllang=en_us,de_de,en_gb
au BufNewFile,BufRead,BufEnter      *.md       setlocal spell      spelllang=en_us,de_de,en_gb
au BufNewFile,BufRead,BufEnter      *.txt      setlocal spell      spelllang=en_us,de_de,en_gb
au BufNewFile,BufRead,BufEnter      *.tex      setlocal spell      spelllang=en_us,de_de,en_gb

"############## Statusline ###############

set laststatus=2

" get rid of additional "-- INSERT --" field below statusline
set noshowmode

" set lightline theme
let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ }

"############### Vimspector ##############
"let g:vimspector_enable_mappings = 'HUMAN'
nmap <leader><F9> :call vimspector#Launch()<CR>
nnoremap <F2> :call vimspector#Reset()<CR>

nmap <F7> <Plug>VimspectorStepInto
nmap <F8> <Plug>VimspectorStepOver
nmap <leader><F8> <Plug>VimspectorStepOut
nnoremap <F9> :call vimspector#Continue()<CR>
nmap <F5> <Plug>VimspectorRestart

nmap <leader>bp <Plug>VimspectorToggleBreakpoint
nmap <leader>cbp <Plug>VimspectorToggleConditionalBreakpoint

":packadd! vimspector
"############### Vimtex ###################

let g:tex_flavor = "latex"
"let g:vimtex_view_method = "Evince"
let g:vimtex_latexmk_options ="-pdf -verbose -file-line-error -synctex=1 -interaction=nonstopmode"
let g:vimtex_quickfix_ignore_all_warnings = 0
let g:polyglot_disabled = ['latex']

"############### Themes ###################

""""""""""""""" Tomorrow """""""""""""""""
"colorscheme Tomorrow-Night-Bright
"
""""""""""""" gruvbox """""""""""""""""""""""
set background=dark
colorscheme gruvbox
""let g:gruvbox_contrast_dark='hard'      "needs to be set before loading the colorscheme
"
"let g:gruvbox_italic=1


""""""""""""""" solarized """"""""""""""""
"set background=dark
"let g:solarized_termcolors=256  " only use this if you don't use solarized
"colors in Xresources
"colorscheme solarized

""""""""""""""" neodark """"""""""""""""""
"colorscheme neodark
"let g:neodark#background = '#000000'
"let g:neodark#use_256color = 1

"""""""""""""" jellybeans """""""""""""""""

"colorscheme jellybeans

"############## Syntax Highlighting ##############

""""""""""""""" C++ """"""""""""""""""""
" source: https://github.com/octol/vim-cpp-enhanced-highlight

let c_no_curly_error=1                    "workaround for vim flagging braces as errors


"############## Vimwiki #######################

let g:vimwiki_list = [
      \{'path': '~/Documents/private/Vimwiki/personal.wiki'},
      \{'path': '~/Documents/private/Vimwiki/studies.wiki'},
      \{'path': '~/Documents/private/Vimwiki/projects.wiki'},
      \{'path': '~/Documents/private/Vimwiki/technical.wiki'}
      \]

""""""""""" Insert Journal Template """"""""""""""

nnoremap <silent><leader>tj :call NewJournal()<CR>

function! NewJournal()
  .-1read ~/.vim/templates/journal
  s/Date/\=strftime("%A, %d. %B %Y")/
endfunction

