#!/bin/bash

# underline color for polybar
underline_color=#0a6cf5 

# determine running player
status=$(playerctl --player=spotify status 2>/dev/null) 
if [[ -z $status ]]; then
  status=$(playerctl --player=cmus status) 
  player='cmus'
else
  player='spotify'
fi

running=0
if [[ $status == 'Playing' ]]; then
  underline_color=#00FF00
  status=
  running=1
elif [[ $status == 'Paused' ]]; then
  underline_color=#FFFF00
  status=
  running=1
fi

artist=$(playerctl --player=$player metadata artist 2>/dev/null)
song=$(playerctl --player=$player metadata title 2>/dev/null) 

out_string="$status  $artist - $song"
#echo $out_string

if [[ $running -eq 1 ]]; then
  if [[ $song == 'Advertisement' && $player == 'spotify' ]]; then
      underline_color=#FF0000
      out_string="$status  blocking ad"
      pactl set-sink-mute @DEFAULT_SINK@ 1
  else 
      pactl set-sink-mute @DEFAULT_SINK@ 0
  fi
  echo -n "%{u$underline_color +u}" "$out_string""%{-u}" 
else 
  echo -n "-"
fi  

